/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WorkspaceCreateRouteImport } from './routes/workspace-create'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as InvitationAcceptanceRouteImport } from './routes/invitation-acceptance'
import { Route as WorkspaceIdRouteImport } from './routes/$workspaceId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIdIndexRouteImport } from './routes/$workspaceId.index'
import { Route as WorkspaceIdPublishRouteImport } from './routes/$workspaceId.publish'
import { Route as WorkspaceIdDocumentsRouteImport } from './routes/$workspaceId.documents'
import { Route as WorkspaceIdDashboardRouteImport } from './routes/$workspaceId.dashboard'
import { Route as WorkspaceIdAiRouteImport } from './routes/$workspaceId.ai'
import { Route as WorkspaceIdDocumentsIndexRouteImport } from './routes/$workspaceId.documents.index'
import { Route as WorkspaceIdDocumentsDocumentIdRouteImport } from './routes/$workspaceId.documents.$documentId'
import { Route as WorkspaceIdDocumentsDocumentIdIndexRouteImport } from './routes/$workspaceId.documents.$documentId.index'
import { Route as WorkspaceIdDocumentsDocumentIdEditRouteImport } from './routes/$workspaceId.documents.$documentId.edit'
import { Route as WorkspaceIdDocumentsDocumentIdCommentsRouteImport } from './routes/$workspaceId.documents.$documentId.comments'
import { Route as WorkspaceIdDocumentsDocumentIdApprovalsRouteImport } from './routes/$workspaceId.documents.$documentId.approvals'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCreateRoute = WorkspaceCreateRouteImport.update({
  id: '/workspace-create',
  path: '/workspace-create',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationAcceptanceRoute = InvitationAcceptanceRouteImport.update({
  id: '/invitation-acceptance',
  path: '/invitation-acceptance',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdIndexRoute = WorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdPublishRoute = WorkspaceIdPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdDocumentsRoute = WorkspaceIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdDashboardRoute = WorkspaceIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdAiRoute = WorkspaceIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdDocumentsIndexRoute =
  WorkspaceIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdDocumentsRoute,
  } as any)
const WorkspaceIdDocumentsDocumentIdRoute =
  WorkspaceIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => WorkspaceIdDocumentsRoute,
  } as any)
const WorkspaceIdDocumentsDocumentIdIndexRoute =
  WorkspaceIdDocumentsDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdDocumentsDocumentIdRoute,
  } as any)
const WorkspaceIdDocumentsDocumentIdEditRoute =
  WorkspaceIdDocumentsDocumentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => WorkspaceIdDocumentsDocumentIdRoute,
  } as any)
const WorkspaceIdDocumentsDocumentIdCommentsRoute =
  WorkspaceIdDocumentsDocumentIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => WorkspaceIdDocumentsDocumentIdRoute,
  } as any)
const WorkspaceIdDocumentsDocumentIdApprovalsRoute =
  WorkspaceIdDocumentsDocumentIdApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => WorkspaceIdDocumentsDocumentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/invitation-acceptance': typeof InvitationAcceptanceRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/workspace-create': typeof WorkspaceCreateRoute
  '/workspaces': typeof WorkspacesRoute
  '/$workspaceId/ai': typeof WorkspaceIdAiRoute
  '/$workspaceId/dashboard': typeof WorkspaceIdDashboardRoute
  '/$workspaceId/documents': typeof WorkspaceIdDocumentsRouteWithChildren
  '/$workspaceId/publish': typeof WorkspaceIdPublishRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
  '/$workspaceId/documents/$documentId': typeof WorkspaceIdDocumentsDocumentIdRouteWithChildren
  '/$workspaceId/documents/': typeof WorkspaceIdDocumentsIndexRoute
  '/$workspaceId/documents/$documentId/approvals': typeof WorkspaceIdDocumentsDocumentIdApprovalsRoute
  '/$workspaceId/documents/$documentId/comments': typeof WorkspaceIdDocumentsDocumentIdCommentsRoute
  '/$workspaceId/documents/$documentId/edit': typeof WorkspaceIdDocumentsDocumentIdEditRoute
  '/$workspaceId/documents/$documentId/': typeof WorkspaceIdDocumentsDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitation-acceptance': typeof InvitationAcceptanceRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/workspace-create': typeof WorkspaceCreateRoute
  '/workspaces': typeof WorkspacesRoute
  '/$workspaceId/ai': typeof WorkspaceIdAiRoute
  '/$workspaceId/dashboard': typeof WorkspaceIdDashboardRoute
  '/$workspaceId/publish': typeof WorkspaceIdPublishRoute
  '/$workspaceId': typeof WorkspaceIdIndexRoute
  '/$workspaceId/documents': typeof WorkspaceIdDocumentsIndexRoute
  '/$workspaceId/documents/$documentId/approvals': typeof WorkspaceIdDocumentsDocumentIdApprovalsRoute
  '/$workspaceId/documents/$documentId/comments': typeof WorkspaceIdDocumentsDocumentIdCommentsRoute
  '/$workspaceId/documents/$documentId/edit': typeof WorkspaceIdDocumentsDocumentIdEditRoute
  '/$workspaceId/documents/$documentId': typeof WorkspaceIdDocumentsDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/invitation-acceptance': typeof InvitationAcceptanceRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/workspace-create': typeof WorkspaceCreateRoute
  '/workspaces': typeof WorkspacesRoute
  '/$workspaceId/ai': typeof WorkspaceIdAiRoute
  '/$workspaceId/dashboard': typeof WorkspaceIdDashboardRoute
  '/$workspaceId/documents': typeof WorkspaceIdDocumentsRouteWithChildren
  '/$workspaceId/publish': typeof WorkspaceIdPublishRoute
  '/$workspaceId/': typeof WorkspaceIdIndexRoute
  '/$workspaceId/documents/$documentId': typeof WorkspaceIdDocumentsDocumentIdRouteWithChildren
  '/$workspaceId/documents/': typeof WorkspaceIdDocumentsIndexRoute
  '/$workspaceId/documents/$documentId/approvals': typeof WorkspaceIdDocumentsDocumentIdApprovalsRoute
  '/$workspaceId/documents/$documentId/comments': typeof WorkspaceIdDocumentsDocumentIdCommentsRoute
  '/$workspaceId/documents/$documentId/edit': typeof WorkspaceIdDocumentsDocumentIdEditRoute
  '/$workspaceId/documents/$documentId/': typeof WorkspaceIdDocumentsDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceId'
    | '/invitation-acceptance'
    | '/sign-in'
    | '/sign-out'
    | '/workspace-create'
    | '/workspaces'
    | '/$workspaceId/ai'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/documents'
    | '/$workspaceId/publish'
    | '/$workspaceId/'
    | '/$workspaceId/documents/$documentId'
    | '/$workspaceId/documents/'
    | '/$workspaceId/documents/$documentId/approvals'
    | '/$workspaceId/documents/$documentId/comments'
    | '/$workspaceId/documents/$documentId/edit'
    | '/$workspaceId/documents/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitation-acceptance'
    | '/sign-in'
    | '/sign-out'
    | '/workspace-create'
    | '/workspaces'
    | '/$workspaceId/ai'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/publish'
    | '/$workspaceId'
    | '/$workspaceId/documents'
    | '/$workspaceId/documents/$documentId/approvals'
    | '/$workspaceId/documents/$documentId/comments'
    | '/$workspaceId/documents/$documentId/edit'
    | '/$workspaceId/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/$workspaceId'
    | '/invitation-acceptance'
    | '/sign-in'
    | '/sign-out'
    | '/workspace-create'
    | '/workspaces'
    | '/$workspaceId/ai'
    | '/$workspaceId/dashboard'
    | '/$workspaceId/documents'
    | '/$workspaceId/publish'
    | '/$workspaceId/'
    | '/$workspaceId/documents/$documentId'
    | '/$workspaceId/documents/'
    | '/$workspaceId/documents/$documentId/approvals'
    | '/$workspaceId/documents/$documentId/comments'
    | '/$workspaceId/documents/$documentId/edit'
    | '/$workspaceId/documents/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceIdRoute: typeof WorkspaceIdRouteWithChildren
  InvitationAcceptanceRoute: typeof InvitationAcceptanceRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  WorkspaceCreateRoute: typeof WorkspaceCreateRoute
  WorkspacesRoute: typeof WorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-create': {
      id: '/workspace-create'
      path: '/workspace-create'
      fullPath: '/workspace-create'
      preLoaderRoute: typeof WorkspaceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation-acceptance': {
      id: '/invitation-acceptance'
      path: '/invitation-acceptance'
      fullPath: '/invitation-acceptance'
      preLoaderRoute: typeof InvitationAcceptanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId': {
      id: '/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/': {
      id: '/$workspaceId/'
      path: '/'
      fullPath: '/$workspaceId/'
      preLoaderRoute: typeof WorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/publish': {
      id: '/$workspaceId/publish'
      path: '/publish'
      fullPath: '/$workspaceId/publish'
      preLoaderRoute: typeof WorkspaceIdPublishRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/documents': {
      id: '/$workspaceId/documents'
      path: '/documents'
      fullPath: '/$workspaceId/documents'
      preLoaderRoute: typeof WorkspaceIdDocumentsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/dashboard': {
      id: '/$workspaceId/dashboard'
      path: '/dashboard'
      fullPath: '/$workspaceId/dashboard'
      preLoaderRoute: typeof WorkspaceIdDashboardRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/ai': {
      id: '/$workspaceId/ai'
      path: '/ai'
      fullPath: '/$workspaceId/ai'
      preLoaderRoute: typeof WorkspaceIdAiRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/documents/': {
      id: '/$workspaceId/documents/'
      path: '/'
      fullPath: '/$workspaceId/documents/'
      preLoaderRoute: typeof WorkspaceIdDocumentsIndexRouteImport
      parentRoute: typeof WorkspaceIdDocumentsRoute
    }
    '/$workspaceId/documents/$documentId': {
      id: '/$workspaceId/documents/$documentId'
      path: '/$documentId'
      fullPath: '/$workspaceId/documents/$documentId'
      preLoaderRoute: typeof WorkspaceIdDocumentsDocumentIdRouteImport
      parentRoute: typeof WorkspaceIdDocumentsRoute
    }
    '/$workspaceId/documents/$documentId/': {
      id: '/$workspaceId/documents/$documentId/'
      path: '/'
      fullPath: '/$workspaceId/documents/$documentId/'
      preLoaderRoute: typeof WorkspaceIdDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof WorkspaceIdDocumentsDocumentIdRoute
    }
    '/$workspaceId/documents/$documentId/edit': {
      id: '/$workspaceId/documents/$documentId/edit'
      path: '/edit'
      fullPath: '/$workspaceId/documents/$documentId/edit'
      preLoaderRoute: typeof WorkspaceIdDocumentsDocumentIdEditRouteImport
      parentRoute: typeof WorkspaceIdDocumentsDocumentIdRoute
    }
    '/$workspaceId/documents/$documentId/comments': {
      id: '/$workspaceId/documents/$documentId/comments'
      path: '/comments'
      fullPath: '/$workspaceId/documents/$documentId/comments'
      preLoaderRoute: typeof WorkspaceIdDocumentsDocumentIdCommentsRouteImport
      parentRoute: typeof WorkspaceIdDocumentsDocumentIdRoute
    }
    '/$workspaceId/documents/$documentId/approvals': {
      id: '/$workspaceId/documents/$documentId/approvals'
      path: '/approvals'
      fullPath: '/$workspaceId/documents/$documentId/approvals'
      preLoaderRoute: typeof WorkspaceIdDocumentsDocumentIdApprovalsRouteImport
      parentRoute: typeof WorkspaceIdDocumentsDocumentIdRoute
    }
  }
}

interface WorkspaceIdDocumentsDocumentIdRouteChildren {
  WorkspaceIdDocumentsDocumentIdApprovalsRoute: typeof WorkspaceIdDocumentsDocumentIdApprovalsRoute
  WorkspaceIdDocumentsDocumentIdCommentsRoute: typeof WorkspaceIdDocumentsDocumentIdCommentsRoute
  WorkspaceIdDocumentsDocumentIdEditRoute: typeof WorkspaceIdDocumentsDocumentIdEditRoute
  WorkspaceIdDocumentsDocumentIdIndexRoute: typeof WorkspaceIdDocumentsDocumentIdIndexRoute
}

const WorkspaceIdDocumentsDocumentIdRouteChildren: WorkspaceIdDocumentsDocumentIdRouteChildren =
  {
    WorkspaceIdDocumentsDocumentIdApprovalsRoute:
      WorkspaceIdDocumentsDocumentIdApprovalsRoute,
    WorkspaceIdDocumentsDocumentIdCommentsRoute:
      WorkspaceIdDocumentsDocumentIdCommentsRoute,
    WorkspaceIdDocumentsDocumentIdEditRoute:
      WorkspaceIdDocumentsDocumentIdEditRoute,
    WorkspaceIdDocumentsDocumentIdIndexRoute:
      WorkspaceIdDocumentsDocumentIdIndexRoute,
  }

const WorkspaceIdDocumentsDocumentIdRouteWithChildren =
  WorkspaceIdDocumentsDocumentIdRoute._addFileChildren(
    WorkspaceIdDocumentsDocumentIdRouteChildren,
  )

interface WorkspaceIdDocumentsRouteChildren {
  WorkspaceIdDocumentsDocumentIdRoute: typeof WorkspaceIdDocumentsDocumentIdRouteWithChildren
  WorkspaceIdDocumentsIndexRoute: typeof WorkspaceIdDocumentsIndexRoute
}

const WorkspaceIdDocumentsRouteChildren: WorkspaceIdDocumentsRouteChildren = {
  WorkspaceIdDocumentsDocumentIdRoute:
    WorkspaceIdDocumentsDocumentIdRouteWithChildren,
  WorkspaceIdDocumentsIndexRoute: WorkspaceIdDocumentsIndexRoute,
}

const WorkspaceIdDocumentsRouteWithChildren =
  WorkspaceIdDocumentsRoute._addFileChildren(WorkspaceIdDocumentsRouteChildren)

interface WorkspaceIdRouteChildren {
  WorkspaceIdAiRoute: typeof WorkspaceIdAiRoute
  WorkspaceIdDashboardRoute: typeof WorkspaceIdDashboardRoute
  WorkspaceIdDocumentsRoute: typeof WorkspaceIdDocumentsRouteWithChildren
  WorkspaceIdPublishRoute: typeof WorkspaceIdPublishRoute
  WorkspaceIdIndexRoute: typeof WorkspaceIdIndexRoute
}

const WorkspaceIdRouteChildren: WorkspaceIdRouteChildren = {
  WorkspaceIdAiRoute: WorkspaceIdAiRoute,
  WorkspaceIdDashboardRoute: WorkspaceIdDashboardRoute,
  WorkspaceIdDocumentsRoute: WorkspaceIdDocumentsRouteWithChildren,
  WorkspaceIdPublishRoute: WorkspaceIdPublishRoute,
  WorkspaceIdIndexRoute: WorkspaceIdIndexRoute,
}

const WorkspaceIdRouteWithChildren = WorkspaceIdRoute._addFileChildren(
  WorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceIdRoute: WorkspaceIdRouteWithChildren,
  InvitationAcceptanceRoute: InvitationAcceptanceRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  WorkspaceCreateRoute: WorkspaceCreateRoute,
  WorkspacesRoute: WorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
